version: "2" 

checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
    config:
      threshold: 200
  similar-code:
    enabled: false
  method-complexity:
    enabled: false
    config:
      threshold: 10
coverage:
  precision: 0
  round: down
  threshold:
    total:
      statements: 80
      branches: 75
      functions: 80
      lines: 80
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
