version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: /app
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy_staging:
    docker:
      - image: docker:latest
    working_directory: /app
    environment:
      IMAGE_NAME: <https://github.com/atlp-rwanda/e-comm-team-brogrammers-fn.git>-staging
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
          docker tag $IMAGE_NAME:$CIRCLE_SHA1 $IMAGE_NAME:latest
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $IMAGE_NAME:$CIRCLE_SHA1
          docker push $IMAGE_NAME:latest
      - deploy:
          name: Deploy Staging
          command: |
            curl -X POST <deploy-staging-webhook-url>   #To be inserted later
