version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

  codeclimate-test-coverage:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests with Coverage
          command: npm run test:coverage
      - run:
          name: Send Test Coverage to CodeClimate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build --exit-code $?
          env:
            CC_TEST_REPORTER_ID: <your-cc-test-reporter-id>
    when: always
    requires:
      - build

workflows:
  build-and-test:
    jobs:
      - build
      - codeclimate-test-coverage
